# Generated by Django 3.2.4 on 2021-06-12 11:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('time_field', models.DateTimeField(help_text='Date and Time the event commences.')),
                ('char_field_1', models.CharField(blank=True, help_text='Short line describing any event organiser', max_length=128, null=True)),
                ('char_field_2', models.CharField(help_text='Very short one-liner describing the event', max_length=128)),
                ('introduction', wagtail.core.fields.RichTextField(blank=True, help_text='Event Introduction', max_length=1500, null=True)),
                ('duration', models.IntegerField(default=120, help_text='Nominal duration of the event in minutes')),
                ('char_field_3', models.CharField(help_text='Very short one-liner describing the event', max_length=128)),
                ('char_field_4', models.CharField(help_text='Very short one-liner describing the event', max_length=128)),
                ('hero_image', models.ForeignKey(help_text='Hero image, at least 800x375, requires landscape crop', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('sub_page', models.ForeignKey(blank=True, help_text='Info page related to the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('datetime_field', models.DateTimeField(help_text='Date and Time the test commences')),
                ('time_field', models.TimeField(blank=True, help_text='Time the test commences', null=True)),
                ('message', wagtail.core.fields.RichTextField(blank=True, help_text='Message needs to have been approved', max_length=300, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_ord', to='testpage.testpage')),
                ('sub_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testpage.testsubpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
